// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TestEf.ConsoleMain.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class v00_00_01_002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v00_00_01_002));
        
        string IMigrationMetadata.Id
        {
            get { return "201408231849047_v00_00_01_002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
